### ISSUE TITLE
ListExpiringPoliciesCommand: suggestions for improvement

### ISSUE THREAD

**Issue by yihuididi** [AY2425S1-CS2103T-T14-1/tp#177]
<img width="720" alt="Screenshot 2024-11-03 at 12 52 20 AM" src="https://github.com/user-attachments/assets/c66fc90d-0d66-4411-82a9-d7ef2ecf9876">
Perhaps should use kebab case (e.g., list-expiring-policies or equivalent) as the command word, to keep things consistent with the other commands.

**Comment by ckaayy** [comment]
good point, i was thinking of changing as well
