### ISSUE TITLE
[PE-D][Tester D] Excessively long claim descriptions may lead to misleading cutoff in text

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-1/tp#281]
In screenshot below, a long description (although unlikely) may lead to incorrect reading of data. This is different from the previous issue as fixing the text overflow for Policy enumeration may differ from that of claims. Alternatively, the overflow may be fixed with ellipsis truncation to indicate a longer text.

![image.png](https://raw.githubusercontent.com/jloh02/ped/main/files/dde4da50-3252-47b3-8e0c-244ad948eb2b.png)

Further width:
![image.png](https://raw.githubusercontent.com/jloh02/ped/main/files/5ce8f974-f7c2-47a8-a10c-085a26f8bdfb.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: jloh02/ped#9

**Comment by Justincjr** [comment]
same UI bug

**Comment by Justincjr** [comment]
not a bug
