### ISSUE TITLE
[PE-D][Tester E] Bug: Names are not automatically capitalised

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-1/tp#289]
Names have a specific format, which is that the first letter should be capitalised. By allowing case-sensitivity, the name data becomes inconsistent and is not saved in the Name format. 
![Screenshot 2024-11-08 at 5.08.57 PM.png](https://raw.githubusercontent.com/yastsc/ped/main/files/d62d5af0-e738-4886-9221-3eee26da99dc.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: yastsc/ped#9

**Comment by Justincjr** [comment]
add to UG

**Comment by Justincjr** [comment]
enhancement
