### ISSUE TITLE
[PE-D][Tester A] Target User reasoning not specified

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-1/tp#312]
![image.png](https://raw.githubusercontent.com/Jaynon/ped/main/files/c6c67aa9-23e3-4112-a774-6f25f9ff46b9.png)

from the developer guide, your target user is specifically Prudential Insurance Agents 

here are some of my concerns:

1. What issues are prudential agents facing?
2. Are there any specialized features that only prudential agents can make use of, and not other insurance agents?

it would be nice if these would be states in the DG

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Jaynon/ped#13

**Comment by Justincjr** [comment]
add in DG
