### ISSUE TITLE
[PE-D][Tester A] Unable to follow appendix instructions

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-1/tp#313]
![image.png](https://raw.githubusercontent.com/Jaynon/ped/main/files/ebe004cb-3875-4484-bcd2-ac7c16f4de53.png)

Double clicking the jar file does not launch the application

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Jaynon/ped#14

**Comment by Justincjr** [comment]
add link to refer to getting started
