### ISSUE TITLE
[PE-D][Tester D] list-expiring-policies amount display issue 

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-1/tp#321]
The premium and coverage amount for expiring policies is missing the "$" unit and may be ambiguous to the user. Although implied, it is inconsistent with the rest of the UI

![image.png](https://raw.githubusercontent.com/jloh02/ped/main/files/9fa46cd0-e50b-4ebe-b1fe-560fc31fb1e8.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: jloh02/ped#19

**Comment by ckaayy** [comment]
not allowed to enhance user messages if its not a bug
