### ISSUE TITLE
[PE-D][Tester D] Definition of duplicate clients not clear

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-1/tp#324]
Clients are considered duplicated when name + phone number are matching. This is not clear to the user and not included in the user guide which may lead to misinterpretations or confusion when the user receives a "This client already exists in Prudy" with no workaround 

![image.png](https://raw.githubusercontent.com/jloh02/ped/main/files/c0a4f6ad-374e-44c0-8ea4-c89485804f31.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: jloh02/ped#22

**Comment by Justincjr** [comment]
add to UG
