### ISSUE TITLE
[PE-D][Tester C] Error in list-claims 

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-1/tp#326]
![image.png](https://raw.githubusercontent.com/jinnsuke/ped/main/files/45e3e2c3-b8f5-4647-89ac-c470e2449cd6.png)

I clearly indicated "health" but I get the error "Policy can only be Life, Health, or Education."

The output message should instead be "No claims available"

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: jinnsuke/ped#13

**Comment by Justincjr** [comment]
wrong command syntax
